[tool.poetry]
name = "vscode_django"
version = "1.0.0"
description = "CLI helpers for the vscode extension"
authors = ["Baptiste Darthenay <baptiste.darthenay@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.4"
tomlkit = "^0.2.0"

[tool.poetry.dev-dependencies]
toml = "^0.9.4"

[tool.poetry.scripts]
build-syntax = "syntaxes.build:main"
